package fr.hopelessworld.sample;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan(basePackages = { "fr.hopelessworld.sample", "fr.hopelessworld.autogenerated" })
public class AngularGeneratorStrategySampleApplication {

	public static void main(String[] args) {
		SpringApplication.run(AngularGeneratorStrategySampleApplication.class, args);
	}
}
